name: SoundsofQJ
favicon: null
layout_spectrum: 0.4931293362751603
typography_spectrum: 0.08335073268972337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8190853248815984
  lightness: 0.9729144144803286
  saturation: 0.6193744949996471
  rhythmicContrast: 0.4998755401466042
purpose: []
